apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: test
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: ikeda0034/puppeteer4
        name: test
        resources: {}
        volumeMounts:
        - mountPath: "/app/data"
          name: mydata
      volumes:
        - name: mydata
          # マウント対象となる Persistent Volume に対応する
          # Persistent Volume Claimを指定
          persistentVolumeClaim:
            claimName: nfs-claim1
      restartPolicy: Never
status: {}
